import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import ClientThemeSync from "~/components/common/theme/clientThemeSync";
import { getThemeFromCookie } from "~/utils/theme";

import "./globals.css";
import BaseLayout from "~/components/layout/container/baseLayout";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Teyvat Archive",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = getThemeFromCookie();

  return (
    <html lang="en" className={theme}>
      <body className={`${openSans.variable} antialiased`} id="app">
        <BaseLayout>{children}</BaseLayout>
        <ClientThemeSync />
      </body>
    </html>
  );
}
